### ISSUE TITLE
Running OpenBSD using xhyve

### ISSUE THREAD

**Issue by zg** [machyve/xhyve#109]
Has anyone had success with running OpenBSD under xhyve? If so, how did you achieve this?

**Comment by iankronquist** [comment]
@zg have you read the [blog post](http://www.pagetable.com/?p=831) which explains how to build your own Linux image for xhyve? I imagine the process would be very similar for OpenBsd.

**Comment by zg** [comment]
It is not similar. In fact, the configuration I have for FreeBSD differs significantly compared to the one within [xhyverun.sh](https://github.com/mist64/xhyve/blob/master/xhyverun.sh).

**Comment by unbalancedparentheses** [comment]
Is this working?

**Comment by brycv** [comment]
I think OpenBSD support depends on UEFI support. I discussed it some time back with Michael Dexter and there is potential but I have not looked further into it. Normally you would use grub2-bhyve to boot an OS like OpenBSD but that is not supported with xhyve. I am quite interested in the ability to run OpenBSD under xhyve as well.

**Comment by lyda** [comment]
I assume the fbsd firmware method won't work here?

**Comment by jeremyhu** [comment]
I expect this should be working with current sources.  Please report back in a new ticket if not (and provide the error you are having).
