### ISSUE TITLE
Move development to a repo owned by multiple people?

### ISSUE THREAD

**Issue by copumpkin** [machyve/xhyve#124]
The development of xhyve seems to be spread across many forks due to difficulty getting things merged into here. Perhaps it's time to create an organization (or at least open up this repo to more collaborators?) and get a few interested parties to be in charge of reviewing/merging/developing?

I see that someone created the https://github.com/xhyve organization but doesn't seem to have done anything with it. There's another https://github.com/xhyve-xyz organization that seems a bit more active, but is still lagging behind this repo, which itself lags several other forks.

**Comment by copumpkin** [comment]
I also just realized that https://github.com/docker/hyperkit is a more radical fork of the same codebase, and as such will be painful to merge back and forth.

Basically, the fragmentation seems like it's likely to cause a lot of confusion and lost work across forks, so it would be good to open up maintainership or shift it to someone who's able to dedicate the time. Or perhaps just declare that Docker's version is the canonical one and everyone should build on top of that?

cc @mist64

**Comment by johnkeates** [comment]
@mist64 are you still with us?

**Comment by Keno** [comment]
I'd like to add a cautious 👍  to this issue. Seems like there's a number of people interested in helping out here, so it'd be nice to declare some fork or another official (or open up development here), to make sure this project moves forward.

**Comment by yurikoles** [comment]
I had created a fork and organization https://github.com/machyve/machyve

**Comment by copumpkin** [comment]
I'm now a bit torn because HyperKit does seem like the most promising fork now, but has unfortunately diverged fairly significantly from xhyve. So either someone takes on the effort of backporting the commercial efforts going into HyperKit or we all just move our focus and efforts over to their repo.

**Comment by johnkeates** [comment]
I'm not sure what thee right approach is, but having an organisation would definitely help.
Regarding what fork and what port:

- xhyve is itself already sort-of a port from bhyve
- HyperKit seems diverged enough to not be 'like bhyve'
- machyve seems more up to date but has a different name while essentially being the same

Having an 'xhyve' organisation would have been nice, but someone stole that, and xhyve-xyz sounds a bit strange. I've opened an issue at xhyve/xhyve to see if someone is there, it seems empty tho. If there is no response I'll see if GitHub can do something here.

**Comment by aphor** [comment]
I filed an abuse complaint to get the zombie xhyve organization removed or otherwise adjudicated.

I cited the GitHub terms C.3. and C.8. and named anyone with a substantial open PR on this repo.

**Comment by johnkeates** [comment]
Excellent. I hope it gets the project structure back on track if we can get it.

**Comment by aphor** [comment]
OK. Neither good nor bad news. I got this reply, and I want to move this forward if possible, with involvement from anyone else in this thread who wants to contribute. I've drafted a response, but since we only get one shot, I want to solicit all of you to be a part of this. Reply stating you'd like to sign on to the response, and I'll share a gist. We can agree on the "charming" language, and then I'll pass it back to Jack for his offer to forward the request.

https://help.github.com/articles/name-squatting-policy/

> Hi Jeremy,
> 
> Thanks for reaching out! I’ve looked over the xhyve account and it’s not dormant (not all activity on GitHub is public) or available for me to release under our name-squatting policy. However, if you’d like to send a polite message to the user asking them to rename their account so you could have the username, we would be happy to send it on your behalf.
> 
> Just to set the expectation here, they are under no obligation to reply. They might be willing to give up the username or they might not. Either way, we will only contact the user on your behalf one time.
> 
> If this sounds good to you, just reply back to me with the charming plea you’d like us to pass along to the user. If you’d like them to contact you directly, please include an email address for response.
> 
> Please let us know if you have any other questions!
> 
> Cheers,
> Jack

The only recourse beyond this would seem to require pursuing trademark infringement. Michael Steil (mist64) has registered xhyve.org, and is redirecting to his github xhyve repo, so I have more than a small suspicion he might own the github account. If not, his absence may make it difficult. I'm not feeling confident.

I think that if this request through Jack does not succeed, I'm in favor of moving development to @yurikoles https://github.com/machyve/machyve organization. @yurikoles how do you feel about OSS project governance? :)

**Comment by yurikoles** [comment]
@aphor thank you for mention. I don't want be governor, since I'm not familiar with code-base, I will be happy to transfer rights to group of adequate people.

**Comment by gamkiller77** [comment]
With the new year have we seen anything move with this?

**Comment by mist64** [comment]
I'm okay with moving ownership of this repo to someone else or an organization. As soon as there is consensus where to transfer it to, I'll be happy to initiate it.

**Comment by jeremyhu** [comment]
We can go with machyve.  I would've preferred that we just rename xhyve-xyz to machyve instead of forking it to yet another github project since that just leads to confusion.  As I stated elsewhere, I just created xhyve-xyz since @mist64 went missing for a long time and didn't respond to any pings on github or email for half a year, and I wanted to try and get motion again.  I don't really have interest in name wars or forking, so I'm glad that we can focus on machyve.

If someone has a pointer to docs for merging projects (or just shutting one down and having it forwarded to another one), I can setup xhyve to forward to machyve.

**Comment by MindTooth** [comment]
Why not use https://github.com/xhyve and https://github.com/xhyve/xhyve.  Seeing as the user has been inactive for three years, I suspect that GitHub would have no issue with giving this to a new governing body.

**Comment by johnkeates** [comment]
@MindTooth We tried that: aphor commented on Oct 11, 2017 about that. They said no.

**Comment by MindTooth** [comment]
So he did, my bad.  Lets hope the new year bring something good.

**Comment by aphor** [comment]
http://www.pagetable.com/?p=922 <-- There's @mist64 moving on to other things.

**Comment by yurikoles** [comment]
He, creator of machyve org is here.
In order to redirect some repo to new address one with admin rights need to rename it and transfer to new org.

But I need to delete my repo before. Just tell me when and who to add as admins to new org

**Comment by aphor** [comment]
I don't have the bandwidth to do the testing right now, but I'll help out if any

1. nobody else volunteers
1. someone else is there to bootstrap the contribution quality policy

**Comment by johnkeates** [comment]
@yurikoles good to hear from you!

**Comment by jeremyhu** [comment]
@yurikoles Ok, go ahead and delete yours, and I'll rename xhyve-xyz to machyve.

**Comment by copumpkin** [comment]
Do any of you have opinions regarding HyperKit? They seem to be the most advanced "fork" of xhyve, but have diverged quite a bit from this one. Does new development under the new organization incorporate the HyperKit changes or does it evolve separately?

**Comment by jeremyhu** [comment]
Or @mist64 , assuming you own https://github.com/xhyve and are willing to release it, we can just use that as it would probably be the least confusing.

**Comment by jeremyhu** [comment]
HyperKit is a slightly different direction but quite interesting.

I was hopping we could re-converge xhyve and bhyve first (or at least get them much more similar that merging the two would be less cumbersome).  We've taken some steps in that regard (brought over bhyve's EFI stack, etc) but it's not yet ready to upstream.

I see xhyve more as an upstream of HyperKit than a fork of HyperKit. There are smaller use cases that don't fit into HyperKit's model and thus I worry we'd loose some interest if everyone decided to switch gears there.

**Comment by yurikoles** [comment]
@jeremyhu, done

**Comment by yurikoles** [comment]
@jeremyhu up?

**Comment by jeremyhu** [comment]
Done.  I think.  Please double check.  I just renamed the project, not the repos.

If @mist64 is willing to let go of the xhyve GH project, I'd rather rename it (again) to xhyve since that would probably be the least confusing =)

**Comment by mist64** [comment]
Yup.

**Comment by yurikoles** [comment]
@mist64 please `Transfer ownership` to `machyve` under this repo settings. 
Thanks.

**Comment by yurikoles** [comment]
@jeremyhu please give @mist64 write access to new org, so he can transfer this repo there.

**Comment by peterlobster** [comment]
@yurikoles @jeremyhu @aphor @mist64 

Was anything decided on how to move forward? I see that machype is currently 73 commits ahead. Has everyone just lost interest? If so, what's the current recommendation? HyperKit?

**Comment by jeremyhu** [comment]
No, we've just been focusing on landing changes in machyve.  @mist64 was added to the org months ago but never acted on the transfer, so there's nothing we can do about it.

**Comment by peterlobster** [comment]
@jeremyhu Thanks for clarifying. So it would be safe to assume the machyve is going to be the future? If so, should I update the Homebrew installation to install from machyne?

**Comment by jeremyhu** [comment]
This is done now.
