### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _os_unfair_lock_lock

### ISSUE THREAD

**Issue by zatarus** [machyve/xhyve#137]
Compiled and run as adviced, I use OSX 10.11.6:

```
git clone https://github.com/mist64/xhyve
cd xhyve
make
./xhyverun.sh 
```

it gives following:

`dyld: lazy symbol binding failed: Symbol not found: _os_unfair_lock_lock`

**Comment by gucchan22** [comment]
@zatarus Apparently, XCode 8.1 SDK has a symbol that is defined only from macOS Sierra (10.12.x)
Adding this variable and execute ```make``` would help.
```export MACOSX_DEPLOYMENT_TARGET ?= $(shell sw_vers -productVersion)```

See also:
https://github.com/jemalloc/jemalloc/issues/494

**Comment by zatarus** [comment]
Thank you, that made it work! I have made `make clean` and compiled as follows:
$ MACOSX_DEPLOYMENT_TARGET = 10.11 make

**Comment by gucchan22** [comment]
I think we have to add the variable to Makefile or something for those who are still using OS X 10.11 to make xhyve run if we're willing to support the version. 
what do you guys think?
