### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by emilwojtaszek** [machyve/xhyve#147]
This project looks awesome, is this still under development?

**Comment by aphor** [comment]
No

**Comment by kbarmen** [comment]
Apart from VirtualBox, are there any alternative around?

**Comment by rickard-von-essen** [comment]
@kbarmen OSS Qemu (in homebrew), and closed source there is _Parallels Desktop for Mac_ and _VMware Fusion_.

**Comment by rickard-von-essen** [comment]
The code here is the base of _Docker for Mac's_ VM, see https://github.com/moby/hyperkit.

**Comment by kbarmen** [comment]
Yes, was about to answer myself about qemu.. .but it is really slow compared to xhyve, I suppose because it doesn't use the hypervisor framework of macos :(  Will look at the hyperkit, maybe there are some tricks to speed things up.

**Comment by kbarmen** [comment]
And, thanks for quick reply! 👍

**Comment by aphor** [comment]
#124 Discusses the continued development effort. Please check that issue for news.

**Comment by dmarion** [comment]
Latest qemu actually can use Hypervisor.framework, it works for me by simply passing `-machine pc,accel=hvf -cpu host` to qemu...

**Comment by clobber** [comment]
>Latest qemu actually can use Hypervisor.framework, it works for me by simply passing -machine pc,accel=hvf -cpu host to qemu...

No, this does not appear to be the case as of QEMU 3.0.0

Passing `-machine pc,accel=hvf -cpu host` or simply `-accel hvf` returns
`-machine accel=hvf: No accelerator found`

QEMU 2.12 added "experimental" support for Apple's Hypervisor.framework which is removed in the latest stable release. `-accel help`
`Possible accelerators: kvm, xen, hax, tcg`

Too bad.

**Comment by llelf** [comment]
> Latest qemu actually can use Hypervisor.framework, it works for me by simply passing -machine pc,accel=hvf -cpu host to qemu...
> 
> No, this does not appear to be the case as of QEMU 3.0.0

Works for me.

**Comment by clobber** [comment]
>Works for me.

That isn't very descriptive. Are you running QEMU 3.0.0 installed via Homebrew. If so, which version of macOS? What output do you get from `-accel help` ?

**Comment by HazCod** [comment]
Can we add a notice on the README that the project is dead and people should use QEMU with the appropriate flags?

**Comment by aphor** [comment]
Nobody but the original repo owner has write access to the repo. :(

**Comment by jeremyhu** [comment]
That was fixed yesterday.
