### ISSUE TITLE
make fails on mac OSX mojave

### ISSUE THREAD

**Issue by jayrosen1576** [machyve/xhyve#148]
I cloned the repo and ran make. This is the output:

> cc src/vmm/io/vlapic.c
> cc src/vmm/io/vpmtmr.c
> cc src/vmm/io/vrtc.c
> src/vmm/io/vrtc.c:60:8: error: packed attribute is unnecessary for 'struct rtcdev' [-Werror,-Wpacked]
> struct rtcdev {
>        ^
> 1 error generated.
> make: *** [build/vmm/io/vrtc.o] Error 1

Any info would be appreciated. Thanks.

**Comment by karstengresch** [comment]
Same here, on two different computers.

**Comment by orklann** [comment]
@jayrosen1576 @karstengresch 
Comment out `__packed` in line 78 in `src/vmm/io/vrtc.c`
```
};//__packed;
```
And run `make` again

**Comment by akram** [comment]
@orklann thanks: I created PR #149 
Maybe you can comment it :)

**Comment by orklann** [comment]
@akram thank you for the PR.
