### ISSUE TITLE
Installation fails with Homebrew

### ISSUE THREAD

**Issue by barnumbirr** [machyve/xhyve#153]
Hello,

I can't seem to install xhyve with Homebrew:

```
[user@host ~]$ brew update
Already up-to-date.
[user@host ~]$ brew install --HEAD xhyve
==> Cloning https://github.com/machyve/xhyve.git
Updating /Users/martin/Library/Caches/Homebrew/xhyve--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at e73e4f1 Merge pull request #119 from zchee/kexec-ramdisk_start
==> make
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - xhyverun.sh
```
Cheers.

**Comment by oholiab** [comment]
If you need a short term fix (you just want it to complete the installation), run `brew edit xhyve` and then swap:

```ruby
    pkgshare.install "xhyverun.sh"
```
for
```ruby
    pkgshare.install "xhyverun-freebsd.sh"
    pkgshare.install "xhyverun-windows.sh"
    pkgshare.install "xhyverun-tinycorelinux.sh"
```
or whichever subset of those you're actually interested in.

**Comment by oholiab** [comment]
> ```ruby
>     pkgshare.install "xhyverun-freebsd.sh"
>     pkgshare.install "xhyverun-windows.sh"
>     pkgshare.install "xhyverun-tinycorelinux.sh"
> ```

I say that, all three of those appear to have a dependency on the `build` directory which isn't installed, so you can either include that or just delete the run scripts from the formula for an interrim fix.

**Comment by charles-gray** [comment]
+1 on this issue

**Comment by jeremyhu** [comment]
> ==> make

Homebrew should be using xcodebuild.  I don't see an issue here.  Please work with Homebrew to update their formulas.
