### ISSUE TITLE
xhyve 0.2.0 problem when using Virtualbox 6

### ISSUE THREAD

**Issue by gctwnl** [machyve/xhyve#157]
I am using xhyve as distributed with brew as part of the docker distribution. When I try to create a machine, docker-machine complains:

    Running pre-create checks...
    Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.0r127566\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads"

I have virtualbox 6, definitely higher than 4 and a machine (apparently created under 5) runs fine under 6.

**Comment by gctwnl** [comment]
My mistake. I took a wrong conclusion that this was xhyve related.

**Comment by jeremyhu** [comment]
I don't see how this could be xhyve related.  That error string doesn't come from xhyve.
