### ISSUE TITLE
docker/xhyve on macOS High Sierra fails

### ISSUE THREAD

**Issue by gctwnl** [machyve/xhyve#158]
Clean homebrew install of docker, docker-machine and xhyve (via brew). No Virtualbox installed on the system. Then:

hermione:~ sysbh$ docker-machine create --driver xhyve default
Running pre-create checks...
Creating machine...
(default) Image cache directory does not exist, creating it at /Users/sysbh/.docker/machine/cache...
(default) No default Boot2Docker ISO found locally, downloading the latest release...
(default) Latest release for github.com/boot2docker/boot2docker is v18.09.0
(default) Downloading /Users/sysbh/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v18.09.0/boot2docker.iso...
(default) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(default) Copying /Users/sysbh/.docker/machine/cache/boot2docker.iso to /Users/sysbh/.docker/machine/machines/default/boot2docker.iso...
(default) Creating VM...
Error creating machine: Error in driver during machine creation: exit status 1

**Comment by jeremyhu** [comment]
You're going to need to provide more information than that.  I don't see any evidence that xhyve was ever even executed.  Please start with docker.
