### ISSUE TITLE
can't boot Redhat 8.1 - vm exit VMX 33

### ISSUE THREAD

**Issue by danmack** [machyve/xhyve#180]
When attempting to boot a stock RH81 system, I get the following running on macOS Catalina 10.15.1.

Booting tinylinux and FreeBSD work fine.  Any ideas?

vm exit[0]
          	reason		VMX
                 rip		0x000000000009e019
                 inst_length	3
                 status		0
                 exit_reason	33
                 qualification	0x0000000000000000
                  inst_type		0
                 inst_error		0

Attempting to boot like this:

$XHYVE \
    -A \
    -m 8G -c 1 \
    -s 0:0,hostbridge \
    -s 2:0,virtio-net \
    -s 3:0,ahci-cd,$BOOTVOLUME \
    -s 4:0,virtio-blk,$DISKFILE \
    -s 31,lpc \
    -l com1,stdio \
    -f kexec,$LIBEXEC/vmlinuz,$LIBEXEC/initrd.img,"earlyprintk=serial console=ttyS0"

**Comment by yyyc514** [comment]
Ditto, but with MX Linux.  Any luck?

**Comment by yyyc514** [comment]
Using the `--HEAD` flag with home-brew resolved this for me... I removed 0.2.0 and installed HEAD.

**Comment by danmack** [comment]
thank you, using --HEAD worked.
