### ISSUE TITLE
Port to AMD SVM

### ISSUE THREAD

**Issue by Technophilus** [machyve/xhyve#195]
The latest Ryzen CPUs are great for development and virtualization. Unfortunately, on macOS desktops with AMD processors, Docker cannot be used because of its hard dependency on Hyperkit. If AMD SVM support (perhaps taken from Virtualbox?) is added to xhyve, that would allow AMD processors to run xhyve. Is there any possibility AMD SVM support will be added to xhyve?

**Comment by miwagner1** [comment]
Last time I checked, Apple does not sell macs that use AMD processors and this project relies on the Apple hypervisor framework. If apple’s own framework does not support the cpu then it probably is never going to happen. Parallels and VMware have both switched to the hypervisor framework with the upcoming macOS 11 that will be released later this year. Apple is planning on removing all kernel extension support.

**Comment by Technophilus** [comment]
And so I assume that means Virtualbox will break as well? That is disappointing; currently the only way to run Docker on a Ryzentosh is to use a Virtualbox VM. That's alright though, if it isn't simple to port to SVM then it probably isn't worth it.
