### ISSUE TITLE
Challenges in porting Bhyve to Xhyve (MAC)?

### ISSUE THREAD

**Issue by lonnietc** [machyve/xhyve#217]
Hello,

I have been searching for a viable VMM (64-bit) to use for a new experimental hypervisor on the x86_64 platform and had come across Bhyve (FreeBSD).  Also, in my searches, I came across your Xhyve (OSX) port and wanted to see if you might be able to tell me about some of the challenges you faced when porting the Bhyve code?

Cheers

**Comment by jeremyhu** [comment]
This isn't a bug report, so closing.  Check out https://www.pagetable.com/?p=831
