### ISSUE TITLE
Check this out: docker on xhyve!

### ISSUE THREAD

**Issue by aredridel** [machyve/xhyve#40]
https://github.com/aredridel/xhyvedocker

**Comment by jbergstroem** [comment]
Not sure that issues is the right place for this, but there's also boot2docker-xhyve: https://github.com/ailispaw/boot2docker-xhyve

**Comment by colby-swandale** [comment]
boot2docker is about to enter deprecation as well so i don't recommend huge amounts of effort being devoted to these projects. There is WIP on a xhyve implementation in [docker-machine](https://github.com/boot2docker/boot2docker-cli) which is considered the successor to boot2docker.

**Comment by aredridel** [comment]
Spiffy!

**Comment by colby-swandale** [comment]
i just realized i linked the wrong project. My bad. i have corrected it in my previous post.

**Comment by nlf** [comment]
the creator of boot2docker-xhyve and i also have [dhyve](https://github.com/nlf/dhyve) to throw in the mix

**Comment by aredridel** [comment]
Sweet!

**Comment by rayshan** [comment]
Here's another project that uses xhyve:
https://github.com/nlf/dlite

Background:
https://blog.andyet.com/2016/01/25/easy-docker-on-osx/

**Comment by nlf** [comment]
hi that's me :) i forgot to link back to it here when i switched gears and wrote dlite

**Comment by rayshan** [comment]
Oops didn't read the name closely, sorry!
