### ISSUE TITLE
Problems routing traffic through the vmnet network interface

### ISSUE THREAD

**Issue by jarias** [machyve/xhyve#42]
Hello

I found this issue working with https://github.com/ailispaw/boot2docker-xhyve, I originally post this issue on the boot2docker-xhyve project so here is the link where the actual details are https://github.com/ailispaw/boot2docker-xhyve/issues/7

Let me know if you need more info.

Thanks.

**Comment by jarias** [comment]
Looks like @ailispaw found a workaround I wonder if this should be put into xhyve or just add to the documentation.

**Comment by VGerris** [comment]
can you post this workaround? I am not familiar with pfctl and how to have the bridge appear (setting network to NAT somewhere?). thank you
